"""AI Dealer — "Ace", the house host who reacts to your play.

Two tiers, so the app is great with zero setup and better with AI available:

* **Rule-based (default):** a hand-written line bank keyed by game event. Instant,
  offline, no dependencies, with anti-repeat so Ace doesn't say the same thing twice.

* **Optional LLM upgrade:** if you set the env var ``CASINO_DEALER_MODEL`` to a local
  Ollama model name (e.g. ``llama3.2:1b``), Ace's line is regenerated by that model
  a moment later for extra personality. It runs on a background thread, times out
  fast, and silently keeps the rule-based line if Ollama isn't running. The AI is a
  *bonus layer* — never a requirement.

Ace speaks in the first person (no third-person pronouns), so the character never
assumes a gender. If the voice module is enabled, each final line is also spoken.
"""
import os
import json
import random
import threading
import urllib.request

import tkinter as tk

import theme
import voice

NAME = "Christopher"

# Rule-based line bank. {amt} is filled from context. Keep lines short + punchy.
LINES = {
    "greeting": [
        "Welcome to Mac Land! Let's make some memories.",
        "Good to see you at my table. Feeling lucky?",
        "Step right up — the chips are hot tonight.",
        "Fresh cards, fresh luck. Let's play.",
    ],
    "win": [
        "Nice one — ${amt} headed your way!",
        "That's how it's done. +${amt}.",
        "Cha-ching! ${amt} for you.",
        "I like your style. ${amt} richer.",
    ],
    "bigwin": [
        "Now THAT'S a hit — ${amt}! Somebody's on fire.",
        "Big money, big money! ${amt}!",
        "Whoa — ${amt}! Save some luck for the rest of us.",
    ],
    "jackpot": [
        "JACKPOT! ${amt}! I've never seen anything like it!",
        "Ring the bell — ${amt}! You broke the machine!",
        "Lucky sevens! ${amt}! Drinks are on you.",
    ],
    "loss": [
        "Tough break. Shake it off — the next one's yours.",
        "The house nudges ahead. Stay in the game.",
        "Ouch. But fortune loves a comeback.",
        "Can't win 'em all. Let's run it back.",
    ],
    "push": [
        "A push — nobody blinks. Your bet's safe.",
        "Dead heat. We go again.",
    ],
    "blackjack": [
        "BLACKJACK! Twenty-one on the nose. Beautiful.",
        "Snapper! Pays three to two — well played.",
    ],
    "bust": [
        "Busted! One card too many. It happens.",
        "Over twenty-one — the table sighs with you.",
    ],
    "point_set": [
        "Point is {point}. Roll it before the seven!",
        "We've got a point — {point}. Back it with odds!",
    ],
    "seven_out": [
        "Seven out. The dice giveth and taketh.",
        "Ah, the seven. Rack 'em up, we go again.",
    ],
    "near": [
        "Soooo close! Almost had it.",
        "A whisker away. I felt that one.",
    ],
    "bold": [
        "Bold move — I respect the swing.",
        "Going big, are we? I love it.",
    ],
    "broke": [
        "Out of chips — grab a buy-in from the lobby, you've got this.",
        "Empty stack. Reload and get back in it.",
    ],
}

_TIMEOUT = 8          # seconds to wait on the local model before giving up


def _model():
    return os.environ.get("CASINO_DEALER_MODEL", "").strip()


def llm_enabled():
    return bool(_model())


def _pick(event, ctx, avoid=None):
    bank = LINES.get(event) or LINES["greeting"]
    choices = [ln for ln in bank if ln != avoid] or bank
    line = random.choice(choices)
    try:
        return line.format(**ctx)
    except (KeyError, IndexError):
        return line


def _llm_line(event, ctx):
    """Ask a local Ollama model for one short in-character line. Returns None on any failure."""
    facts = ", ".join(f"{k}={v}" for k, v in ctx.items()) or "none"
    prompt = (
        f"You are {NAME}, a smooth, upbeat casino dealer at Mac Land Casino. "
        f"The player just had this event in {ctx.get('game', 'a game')}: '{event}'. "
        f"Details: {facts}. "
        "Say ONE short, punchy line to the player (max 12 words). "
        "First person only. No emoji. No quotes. Keep it fun and encouraging."
    )
    body = json.dumps({
        "model": _model(),
        "prompt": prompt,
        "stream": False,
        "options": {"num_predict": 40, "temperature": 0.9},
    }).encode()
    try:
        req = urllib.request.Request("http://localhost:11434/api/generate", data=body,
                                     headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=_TIMEOUT) as resp:
            out = json.loads(resp.read()).get("response", "").strip()
        out = out.splitlines()[0].strip().strip('"').strip() if out else ""
        return out[:120] if out else None
    except Exception:
        return None


class DealerBox:
    """A compact dealer strip (name + line + voice toggle) plus a ``react`` method.
    Mount one per game window and call ``react(event, **ctx)`` on game events."""

    def __init__(self, parent, win, felt=theme.NIGHT):
        self.win = win
        self._last = None
        self._seq = 0

        self.frame = tk.Frame(parent, bg=felt)
        top = tk.Frame(self.frame, bg=felt)
        top.pack(fill="x")
        tk.Label(top, text=f"🎙  {NAME.upper()}", font=("Georgia", 10, "bold"),
                 bg=felt, fg=theme.GOLD).pack(side="left", padx=(2, 8))
        self.voice_btn = tk.Button(top, text="🔈  Voice: off", font=("Segoe UI", 8, "bold"),
                                   bg=theme.NIGHT2, fg=theme.GOLD, activebackground="#232b4d",
                                   relief="flat", bd=0, padx=8, pady=2, cursor="hand2",
                                   command=self._toggle_voice)
        self.voice_btn.pack(side="right", padx=2)
        if not voice.available():
            self.voice_btn.config(state="disabled", text="🔈  Voice: n/a")

        self.line = tk.Label(self.frame, text="", font=("Segoe UI", 10, "italic"),
                             bg=felt, fg=theme.IVORY, wraplength=460, justify="left", anchor="w")
        self.line.pack(fill="x", pady=(1, 0))

    def pack(self, **kw):
        self.frame.pack(**kw)
        return self

    def _toggle_voice(self):
        on = voice.toggle()
        self.voice_btn.config(text="🔊  Voice: on" if on else "🔈  Voice: off")
        if on and self._last:
            voice.speak(self._last)

    def react(self, event, **ctx):
        """Show (and optionally speak) a dealer line for a game event."""
        line = _pick(event, ctx, avoid=self._last)
        self._last = line
        self.line.config(text=line)
        voice.speak(line)

        if llm_enabled():                             # optional richer line, off the UI thread
            self._seq += 1
            seq = self._seq
            threading.Thread(target=self._upgrade, args=(event, ctx, seq), daemon=True).start()

    def _upgrade(self, event, ctx, seq):
        line = _llm_line(event, ctx)
        if not line:
            return

        def apply():
            if seq != self._seq:                      # a newer event already superseded this one
                return
            self._last = line
            self.line.config(text=line)
            voice.speak(line)
        self.win.after(0, apply)
